C4Context
    title System Context diagram for extracting data from the Content Store

    Boundary(mirror, "Project: govuk-s3-mirror") {
        Boundary(bucket_mirror, "Bucket: govuk-s3-mirror_govuk-integration-database-backups") {
            System(backup_file, "Object: mongo-api/YYYY-MM-DDTHH:MM:SS-content_store_production.gz")
        }
    }

    Boundary(govuk-knowlege-graph, "Project: govuk-knowledge-graph") {
        Boundary(compute_instance, "Compute Instance: mongodb") {
            System(mongodb, "MongoDB database")
            System(python, "Python scripts")
        }
        Boundary(bucket_data_processed, "Bucket: govuk-knowledge-graph-data-processed") {
            System(url_csv_gz, "Object: content-store/url.csv.gz")
            System(transaction_content_gz, "Object: content-store/transaction_content.csv.gz")
            System(place_content_gz, "Object: content-store/place_content.csv.gz")
            System(content_gz, "Object: content-store/content.csv.gz")
        }
        Boundary(dataset_content, "BigQuery Dataset: content") {
            System(table_url, "Table: url")
            System(content_table, "Table: content")
        }
    }

    Rel(backup_file, mongodb, "")
    Rel(mongodb, url_csv_gz, "")
    Rel(mongodb, python, "")
    Rel(url_csv_gz, table_url, "BigQuery API")
    Rel(transaction_content_gz, content_table, "BigQuery query (concatenate)")
    Rel(place_content_gz, content_table, "BigQuery query (concatenate)")
    Rel(content_table, content_gz, "BigQuery export")


UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
UpdateRelStyle(backup_file, mongodb, $offsetY="-30", $offsetX="20")
