name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-data-community"
      CF_SPACE: "sandbox"

    steps:
      - uses: actions/checkout@v2

      - name: Install the CF CLI
        run: |
          wget https://s3-us-west-1.amazonaws.com/v7-cf-cli-releases/releases/v7.2.0/cf7-cli-installer_7.2.0_x86-64.deb
          sudo dpkg -i cf7-cli-installer_7.2.0_x86-64.deb
      - name: Authenticate
        env:
          # CF_USERNAME and CF_PASSWORD are used by the `cf auth` command to login
          # We use an environment variable instead of passing the details as options using -u / -p to reduce the risk of them being recorded in logs
          # https://cli.cloudfoundry.org/en-US/v6/auth.html
          CF_USERNAME: "data-tech-docs@digital.cabinet-office.gov.uk"
          CF_PASSWORD: "${{ secrets.CF_PASSWORD }}"
        run: |
          echo "Logging into $CF_ORG/$CF_SPACE..."
          echo "1. running 'cf api'"
          cf api "${CF_API}"
          echo "2. running 'cf auth'"
          cf auth
          echo "3. running 'cf target'"
          cf target -o "${CF_ORG}" -s "${CF_SPACE}"
      # Parse app name from manifest to ensure it matches up
      - name: Fetch app name from manifest
        run: echo "APP_NAME=$(ruby -e "require 'yaml'; config = YAML.load_file('manifest.yml'); puts config['applications'][0]['name']")" >> $GITHUB_ENV

      - name: Cancel any existing running deploys to avoid conflict
        run:  |
          echo "Cancelling any previous deployments in progress"
          cf cancel-deployment $APP_NAME || true
      - name: Deploy to PaaS
        # Deploy app and set up app healthcheck https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html
        run: |
          echo "Deploying $APP_NAME to $CF_ORG/$CF_SPACE..."
          cf push $APP_NAME --strategy rolling
          cf logout
